spring:
  application:
    name: person
  webflux:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    username: root
    password: root
  flyway:
    enabled: false
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    url: ${spring.datasource.url}

logging:
  level:
    web: INFO
    org:
      springframework:
        jdbc: DEBUG

