@HOST=http://localhost:8080

### GET request to example server
GET {{HOST}}/persons

###
POST {{HOST}}/persons
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "profilePhotoUrl": "/images/john.png",
  "birthDate": "1990-01-01"
}

###
POST {{HOST}}/persons
Content-Type: application/json
Accept: application/json

{
  "contactInfo":[],
  "address":[],
  "socialMediaAccount":[
    {
      "platform":"FACEBOOK",
      "handle":"xxxb"
    }
  ],
  "firstName":"D V ",
  "lastName":"Ramana",
  "birthDate":"2022-06-11"
}

###
GET {{HOST}}/persons/1

###
PUT {{HOST}}/persons/1
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "profilePhotoUrl": "/images/john.png",
  "birthDate": "1990-01-02"
}

###
PATCH {{HOST}}/persons/1
Content-Type: application/json
Accept: application/json

{
  "birthDate": "1990-01-03"
}

###
DELETE {{HOST}}/persons/1